export const TYPES_SUPPORT_BOOKS = {
  SUPPORT_PDF_TYPE: 'support_pdf',
  SUPPORT_VIDEO_TYPE: 'support_video',
  SUPPORT_WEB_TYPE: 'support_web'
}

export const TYPES_CAREERS = {
  ITI: 'INGENIERIA EN TECNOLOGIAS DE LA INFORMACION',
  IE: 'INGENIERIA EN ENERGIA',
  IET: 'INGENIERIA EN ELECTRONICA Y TELECOMUNICACIONES',
  II: 'INGENIERIA INDUSTRIAL'
}

export const API_URL = import.meta.env.VITE_API_URL || 'http://172.16.1.46:3004/'

export const subjectsArray = [
  'MATEMÁTICAS DISCRETAS',
  'HARDWARE II',
  'PROGRAMACIÓN ORIENTADA A OBJETOS I',
  'REDES I',
  'SISTEMAS OPERATIVOS I',
  'FUNDAMENTOS DE VISIÓN EMPRESARIAL',
  'PROGRAMACIÓN ORIENTADA A OBJETOS II',
  'ESTRUCTURAS DE DATOS',
  'REDES II',
  'CONTABILIDAD',
  'SISTEMAS OPERATIVOS II',
  'ORGANIZACIÓN EMPRESARIAL',
  'FORMULACIÓN Y EVALUACIÓN DE PROYECTOS',
  'BASES DE DATOS I',
  'REDES III',
  'INGENIERÍA DE SOFTWARE I',
  'ADMINISTRACIÓN DE PROYECTOS DE INFORMACIÓN',
  'INTELIGENCIA DE NEGOCIOS',
  'BASES DE DATOS II',
  'INGENIERÍA DE SOFTWARE II',
  'COMERCIO ELECTRÓNICO',
  'SEMINARIO DE LIDERAZGO',
  'ALMACENES DE DATOS',
  'PROGRAMACIÓN WEB I',
  'INGENIERÍA DE SOFTWARE III',
  'DESARROLLO DE EMPRENDEDORES',
  'Sistemas Integrales I',
  'INVESTIGACION DE OPERACIONES',
  'Minería de Datos',
  'PROGRAMACIÓN WEB II',
  'PROGRAMACIÓN VISUAL',
  'CADENA DE SUMINISTROS',
  'SISTEMAS INTEGRALES II',
  'ADMINISTRACIÓN DE CENTROS DE DATOS',
  'Administración de Portales WEB',
  'SEMINARIO DE INVESTIGACIÓN',
  'PROBABILIDAD Y ESTADÍSTICA',
  'QUÍMICA',
  'HERRAMIENTAS OFIMÁTICAS',
  'INTRODUCCIÓN A LA INGENIERÍA',
  'MATEMÁTICAS I',
  'COMUNICACIÓN ORAL Y ESCRITA I',
  'INTRODUCCIÓN A LA PROGRAMACIÓN',
  'FÍSICA',
  'MATEMÁTICAS II',
  'COMUNICACIÓN ORAL Y ESCRITA II',
  'ENERGÍAS 1'
]

export const keywordPages = {
  HOME_PAGE: {
    name: 'Inicio',
    path: 'home'
  },
  ADD_PAGE: {
    name: 'Agregar',
    path: 'add'
  },
  REGISTERS_PAGE: {
    name: 'Registro de Maestros',
    path: 'registers'
  }
}
